In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
accounts=pd.read_csv('accounts.csv')

In [4]:
dictionary=pd.read_csv('data_dictionary.csv')

In [5]:
products=pd.read_csv('products.csv')

In [6]:
pipeline=pd.read_csv('sales_pipeline.csv')

In [7]:
teams=pd.read_csv('sales_teams.csv')

In [8]:
accounts.head(85)

,account,sector,year_established,revenue,employees,office_location,subsidiary_of
0,Acme Corporation,technolgy,1996,1100.04,2822,United States,NaN
1,Betasoloin,medical,1999,251.41,495,United States,NaN
2,Betatech,medical,1986,647.18,1185,Kenya,NaN
3,Bioholding,medical,2012,587.34,1356,Philipines,NaN
4,Bioplex,medical,1991,326.82,1016,United States,NaN
...,...,...,...,...,...,...,...
80,Zathunicon,retail,2010,71.12,144,United States,NaN
81,Zencorporation,technolgy,2011,40.79,142,China,NaN
82,Zoomit,entertainment,1992,324.19,978,United States,NaN
83,Zotware,software,1979,4478.47,13809,United States,NaN
84,Zumgoity,medical,1984,441.08,1210,United States,NaN

In [9]:
dictionary.head()

      Table             Field                          Description
0  accounts           account                         Company name
1  accounts            sector                             Industry
2  accounts  year_established                     Year Established
3  accounts           revenue  Annual revenue (in millions of USD)
4  accounts         employees                  Number of employees

In [10]:
products.head()

        product series  sales_price
0     GTX Basic    GTX          550
1       GTX Pro    GTX         4821
2    MG Special     MG           55
3   MG Advanced     MG         3393
4  GTX Plus Pro    GTX         5482

In [11]:
pipeline.head()

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514.0
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517.0

In [12]:
teams.head()

         sales_agent           manager regional_office
0      Anna Snelling  Dustin Brinkmann         Central
1     Cecily Lampkin  Dustin Brinkmann         Central
2  Versie Hillebrand  Dustin Brinkmann         Central
3    Lajuana Vencill  Dustin Brinkmann         Central
4        Moses Frase  Dustin Brinkmann         Central

In [13]:
accounts.isnull().sum()

account              0
sector               0
year_established     0
revenue              0
employees            0
office_location      0
subsidiary_of       70
dtype: int64

In [14]:
dictionary.isnull().sum()

Table          0
Field          0
Description    0
dtype: int64

In [15]:
products.isnull().sum()

product        0
series         0
sales_price    0
dtype: int64

In [16]:
pipeline.isnull().sum()

opportunity_id       0
sales_agent          0
product              0
account           1425
deal_stage           0
engage_date        500
close_date        2089
close_value       2089
dtype: int64

In [17]:
teams.isnull().sum()

sales_agent        0
manager            0
regional_office    0
dtype: int64

In [18]:
accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   account           85 non-null     object
 1   sector            85 non-null     object
 2   year_established  85 non-null     int64
 3   revenue           85 non-null     float64
 4   employees         85 non-null     int64
 5   office_location   85 non-null     object
 6   subsidiary_of     15 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 4.8+ KB

In [19]:
pipeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   opportunity_id  8800 non-null   object
 1   sales_agent     8800 non-null   object
 2   product         8800 non-null   object
 3   account         7375 non-null   object
 4   deal_stage      8800 non-null   object
 5   engage_date     8300 non-null   object
 6   close_date      6711 non-null   object
 7   close_value     6711 non-null   float64
dtypes: float64(1), object(7)
memory usage: 550.1+ KB

In [20]:
pipeline = pipeline.drop_duplicates()

In [21]:
pipeline['engage_date']=pd.to_datetime(pipeline['engage_date'])

In [22]:
pipeline['close_date']=pd.to_datetime(pipeline['close_date'])

In [23]:
pipeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   opportunity_id  8800 non-null   object
 1   sales_agent     8800 non-null   object
 2   product         8800 non-null   object
 3   account         7375 non-null   object
 4   deal_stage      8800 non-null   object
 5   engage_date     8300 non-null   datetime64[ns]
 6   close_date      6711 non-null   datetime64[ns]
 7   close_value     6711 non-null   float64
dtypes: datetime64[ns](2), float64(1), object(5)
memory usage: 550.1+ KB

In [24]:
pipeline['close_value']=pipeline['close_value'].fillna(0)

In [25]:
pipeline[['engage_date', 'close_date']].isnull().sum()

engage_date     500
close_date     2089
dtype: int64

In [26]:
pipeline['close_value']=pipeline['close_value'].astype(int)

In [27]:
teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sales_agent      35 non-null     object
 1   manager          35 non-null     object
 2   regional_office  35 non-null     object
dtypes: object(3)
memory usage: 972.0+ bytes

In [28]:
teams=teams.drop_duplicates()

In [29]:
teams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sales_agent      35 non-null     object
 1   manager          35 non-null     object
 2   regional_office  35 non-null     object
dtypes: object(3)
memory usage: 972.0+ bytes

In [30]:
accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   account           85 non-null     object
 1   sector            85 non-null     object
 2   year_established  85 non-null     int64
 3   revenue           85 non-null     float64
 4   employees         85 non-null     int64
 5   office_location   85 non-null     object
 6   subsidiary_of     15 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 4.8+ KB

In [31]:
accounts=accounts.drop_duplicates()

In [32]:
accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   account           85 non-null     object
 1   sector            85 non-null     object
 2   year_established  85 non-null     int64
 3   revenue           85 non-null     float64
 4   employees         85 non-null     int64
 5   office_location   85 non-null     object
 6   subsidiary_of     15 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 4.8+ KB

In [33]:
pipeline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   opportunity_id  8800 non-null   object
 1   sales_agent     8800 non-null   object
 2   product         8800 non-null   object
 3   account         7375 non-null   object
 4   deal_stage      8800 non-null   object
 5   engage_date     8300 non-null   datetime64[ns]
 6   close_date      6711 non-null   datetime64[ns]
 7   close_value     8800 non-null   int64
dtypes: datetime64[ns](2), int64(1), object(5)
memory usage: 550.1+ KB

In [34]:
accounts.isnull().sum()

account              0
sector               0
year_established     0
revenue              0
employees            0
office_location      0
subsidiary_of       70
dtype: int64

In [37]:
import sqlite3

conn = sqlite3.connect("sales.db")

In [38]:
accounts.to_sql("accounts", conn, index=False)

products.to_sql("products", conn, index=False)

pipeline.to_sql("sales_pipeline", conn, index=False)

teams.to_sql("sales_teams", conn, index=False)

ValueError: Table 'accounts' already exists.

In [39]:
query = """
SELECT
    product,
    SUM(close_value) AS total_sales
FROM sales_pipeline
WHERE deal_stage = 'Won'
GROUP BY product
ORDER BY total_sales DESC;
"""

total_sales_by_product = pd.read_sql(query, conn)
print(total_sales_by_product)

          product  total_sales
0          GTXPro      3510578
1    GTX Plus Pro      2629651
2     MG Advanced      2216387
3  GTX Plus Basic       705275
4       GTX Basic       499263
5         GTK 500       400612
6      MG Special        43768

In [40]:
query = """
SELECT product,
SUM(close_value)
FROM sales_pipeline
GROUP BY product;
"""

sell_by_product = pd.read_sql(query, conn)
print(sell_by_product)

          product  SUM(close_value)
0         GTK 500            400612
1       GTX Basic            499263
2  GTX Plus Basic            705275
3    GTX Plus Pro           2629651
4          GTXPro           3510578
5     MG Advanced           2216387
6      MG Special             43768

In [41]:
query="""
SELECT COUNT(opportunity_id)
FROM sales_pipeline;
"""

count_of_product_id=pd.read_sql(query,conn)
print(count_of_product_id)

   COUNT(opportunity_id)
0                   8800

In [42]:
query="""
SELECT SUM(close_value) AS total_revenue
FROM sales_pipeline
WHERE deal_stage='Won';
"""
total_revenue=pd.read_sql(query,conn)
print(total_revenue)

   total_revenue
0       10005534

In [43]:
query="""
SELECT AVG(close_value) AS average_deal
FROM sales_pipeline
WHERE deal_stage='Won';
"""
avg_deal=pd.read_sql(query,conn).round(2)
print(avg_deal)

   average_deal
0       2360.91

In [44]:
query="""
SELECT
product,
SUM(close_value) AS revenue

FROM sales_pipeline

WHERE deal_stage='Won'

GROUP BY product

ORDER BY revenue DESC

LIMIT 5;
"""
revenue_by_product=pd.read_sql(query,conn).round(2)
print(revenue_by_product)

          product  revenue
0          GTXPro  3510578
1    GTX Plus Pro  2629651
2     MG Advanced  2216387
3  GTX Plus Basic   705275
4       GTX Basic   499263

In [45]:
query="""
SELECT

sales_agent,
SUM(close_value) AS revenue

FROM sales_pipeline

WHERE deal_stage='Won'

GROUP BY sales_agent

ORDER BY revenue DESC LIMIT 10;
"""
revenue_by_agent=pd.read_sql(query,conn).round(2)
print(revenue_by_agent)

       sales_agent  revenue
0  Darcel Schlecht  1153214
1   Vicki Laflamme   478396
2  Kary Hendrixson   454298
3     Cassey Cress   450489
4    Donn Cantrell   445860
5     Reed Clapper   438336
6        Zane Levy   430068
7    Corliss Cosme   421036
8   James Ascencio   413533
9  Daniell Hammack   364229

In [46]:
query="""
SELECT

a.sector,

SUM(sp.close_value) AS revenue

FROM sales_pipeline sp

JOIN accounts a

ON sp.account=a.account

WHERE sp.deal_stage='Won'

GROUP BY a.sector

ORDER BY revenue DESC;
"""
revenue_by_sector=pd.read_sql(query,conn).round(2)
print(revenue_by_sector)

               sector  revenue
0              retail  1867528
1           technolgy  1515487
2             medical  1359595
3            software  1077934
4             finance   950908
5           marketing   922321
6       entertainment   689007
7  telecommunications   653574
8            services   533006
9          employment   436174

In [47]:
query="""
SELECT

st.regional_office,

SUM(sp.close_value) AS revenue

FROM sales_pipeline sp

JOIN sales_teams st

ON sp.sales_agent=st.sales_agent

GROUP BY st.regional_office;
"""
revenue_by_office=pd.read_sql(query,conn).round(2)
print(revenue_by_office)

  regional_office  revenue
0         Central  3346293
1            East  3090594
2            West  3568647

In [48]:
query="""
SELECT

deal_stage,

COUNT(*) AS total

FROM sales_pipeline

GROUP BY deal_stage;
"""
count_of_deal_stage=pd.read_sql(query,conn).round(2)
print(count_of_deal_stage)

    deal_stage  total
0     Engaging   1589
1         Lost   2473
2  Prospecting    500
3          Won   4238

In [49]:
query="""
SELECT

account,

SUM(close_value) AS revenue

FROM sales_pipeline

WHERE deal_stage='Won'

GROUP BY account

ORDER BY revenue DESC LIMIT 20;
"""
revenue_by_account=pd.read_sql(query,conn).round(2)
print(revenue_by_account)

                 account  revenue
0               Kan-code   341455
1                  Konex   269245
2                 Condax   206410
3                 Cheers   198020
4               Hottechi   194957
5             Goodsilron   182522
6              Treequote   176751
7              Warephase   170046
8             Xx-holding   169357
9                  Isdom   164683
10          Singletechno   163339
11             Mathtouch   163339
12              Scotfind   162725
13             Plussunin   155195
14  Umbrella Corporation   152701
15              Rangreen   151777
16           Donquadtech   147976
17               Plexzap   144976
18            Stanredtax   142711
19                 Inity   141858

In [50]:
query="""
SELECT

strftime('%m',close_date) AS month,

SUM(close_value)

FROM sales_pipeline

WHERE deal_stage='Won'

GROUP BY month;
"""
sales_in_each_month=pd.read_sql(query,conn).round(2)
print(sales_in_each_month)

  month  SUM(close_value)
0    03           1134672
1    04            721932
2    05           1025713
3    06           1338466
4    07            696932
5    08           1050059
6    09           1235264
7    10            731980
8    11            938943
9    12           1131573

In [51]:
result=pd.read_sql(query,conn)

result.head()

  month  SUM(close_value)
0    03           1134672
1    04            721932
2    05           1025713
3    06           1338466
4    07            696932

In [52]:
product_sales = pd.read_sql(query, conn)

In [53]:
product_sales.to_csv("product_sales.csv", index=False)

In [55]:
accounts.to_csv("accounts_clean.csv", index=False)
products.to_csv("products_clean.csv", index=False)
pipeline.to_csv("sales_pipeline_clean.csv", index=False)
teams.to_csv("sales_teams_clean.csv", index=False)